version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5001:5000"
    volumes:
      - ./server:/app/server
      - ./server/uploads:/app/server/uploads
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://database:27017/designsight
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=5000

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5001
      - REACT_APP_API_BASE_URL=http://localhost:5001

  database:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: {}